---
title: "Map languages in Switzerland"
author: "Duc-Quang Nguyen | swissinfo.ch"
date: "25-08-2016"
output: 
  html_document:
    toc: true
    toc_depth: 3
    theme: simplex
---

```{r settings}
translation.file <- "input/map language and population density - Sheet1.csv"

foreigner.file <- 'input/foreignersByMunicipality2015.csv'
district.file <- "input/districtCH_map.csv"
language.file <- "input/languages.csv"
cities.file <- "input/cities.csv"
densityPop.file <- "input/swissPopDensity.csv"

colourText_bkbg <- '#ffffff'
border.color <- "#404040"
```

```{r packages, include = F}
library(readr)
library(stringi)
library(tidyr)
library(dplyr)
library(magrittr)
library(countrycode)
library(ggplot2)
library(scales)
library(swiMap)
library(swiTheme)
require(rgdal)
require(rgeos)
require(maptools)
library(htmltools)
library(ggiraph)
library(swiRcharts)
require(viridis)
```

```{r load data, include = F}
txt <- read.csv(translation.file, row.names = 1, stringsAsFactors = F)
# discard incomplete translations
cidx <- unique(which(txt =="" | is.na(txt), T)[,2])
if(length(cidx > 0)) {
  warning(paste(colnames(txt)[cidx], collapse = "\t"), " languages will be discarded!", "\n")
  txt <- txt[,-cidx, drop = F]
}
colnames(txt)


fo.df <- read.csv(foreigner.file)

di.df <- read.csv(district.file)
langRegions <- read.csv(language.file) %>% rename (lang = x)
stopifnot(nrow(di.df) == nrow(langRegions))
di.df <- cbind(di.df, langRegions)

## cities
cities <- read_csv(cities.file) %>% rename(pop = size)
densityPop <- read.csv(densityPop.file)

## swiss map shapefiles
path <- getPathShp('CH', 2014)

mu <- spTransform(readOGR(path, layer = "municipalities"), CRS("+init=epsg:4326"))
mu.df <- formatShp(mu) %>% 
  select(long, lat, order, hole, id, group, NAME, EINWOHNERZ, BFS_NUMMER)
mu.df$id <- as.numeric(mu.df$id)

# laod also 2015 municipality shapefiles
ge <- spTransform(readOGR( getPathShp('CH', 2015), layer = "municipalities"), CRS("+init=epsg:4326"))
ge.df <- formatShp(ge) %>% 
  select(long, lat, order, hole, id, group, GEMNAME, BFSNR)
ge.df$id <- as.numeric(ge.df$id)

ca <- spTransform( readOGR(path, layer = "cantons"), CRS("+init=epsg:4326"))
ca.df <- formatShp(ca) %>% select(long, lat, order, hole, id, group, NAME, EINWOHNERZ)
ca.df$id <- as.numeric(ca.df$id)

co <- spTransform(readOGR(path, layer = 'country'), CRS("+init=epsg:4326"))
co.df <- formatShp(co) %>% select(long, lat, order, hole, id, group, NAME, EINWOHNERZ)
co.df$id <- as.numeric(co.df$id)

la <- spTransform( readOGR(path, layer = "lakes"), CRS("+init=epsg:4326"))
la.df <- formatShp(la) %>% select(long, lat, order, hole, id, group)
la.df$id <- as.numeric(la.df$id)
```

```{r map helper, include = F}
# helper mapping 
bk_mapTheme <- function(
  base_size = 14, base_family = "OpenSans-CondensedLight",
  title_family = "OpenSans-CondensedBold", subtitle_family = "OpenSans-CondensedLight",
  bg.colour = '#1a0000', colour = colourText_bkbg
 ) {
     swi_theme(
       y_gridlines = F, base_size = base_size, base_family = base_family, 
       title_family = title_family, subtitle = subtitle_family
     ) + 
    theme(
      panel.background = element_rect(fill = bg.colour, size = 0),
      plot.background = element_rect(fill = bg.colour, size = 0),
      axis.line = element_blank(),
      axis.ticks = element_blank(), 
      axis.title = element_blank(), 
      axis.text = element_blank(),
      plot.title = element_text(colour = colour), 
      plot.subtitle = element_text(colour = "white", margin=margin(b=13)),
      plot.caption = element_text(colour = colour),
      legend.text = element_text(colour = colourText_bkbg, size = 9.5, hjust = 1),
      legend.title = element_text(colour = colourText_bkbg, size = 11),
      legend.key.width = unit(17, "lines"),
      legend.key.height = unit(8, "lines"),
      legend.position = "top",
      legend.title.align = 0,
      plot.margin = unit(c(0.25, 0, 0.1, 0), "cm")
    ) 
}
```

```{r map language}

lang <- 'FR'
for (lang in colnames(txt)) {

  # duplicate data for tranlsations
  largeAgglo <- cities
  ddd <- di.df
  # get translations
  largeAgglo$label <- txt[c('Zürich', 'Genève', 'Basel', 'Bern', 'Lausanne'), lang]
  langLabel <- factor(
             paste0(" ", txt[c('de', 'fr', 'it', 'defr', 'dero'), lang], "  "),
    levels = paste0(" ", txt[c('de', 'fr', 'it', 'defr', 'dero'), lang], "  ")
    )
  names(langLabel) <- c('Allemand','Français', 'Italien', 
                         'Allemand Français', 'Allemand Romanche')
  ddd$lang <- langLabel[match(ddd$lang, names(langLabel))]
 
  #### language map
  lmap <- ggplot() + 
  geom_polygon(data = ddd,
    aes(x = long, y = lat, fill = lang, group = group), 
    colour = NA, size = 0, linetype = 0) +
  coord_quickmap(expand = F) + bk_mapTheme() +
  geom_polygon(
    data = la.df,  aes(x = long, y = lat, group = group),
    size = 0, fill = border.color, colour = border.color) + 
  scale_fill_manual(name = "",
    values = c('#ab3d3f', '#366096', '#3a9736', '#336666', '#ac673e'))

  lmap <- lmap <- lmap + geom_point(data = largeAgglo,
      aes(x = lon, y = lat, size = pop, group = 1),         
      alpha = 0.85, colour = colourText_bkbg, shape = 1
    ) + 
    geom_text(
      data = largeAgglo,
      aes(x = lon, y = lat, group = 1, label = label),
      family = txt['base.font', lang],
      colour = colourText_bkbg,
      nudge_y = -0.082,
      size = 4.2
    )  + scale_size(name = txt['agglosize', lang], range = c(3,7)) +
    geom_text(
      data = largeAgglo,
      aes(x = lon, y = lat, group = 1, label = label),
      family = txt['base.font', lang],
      colour = colourText_bkbg,
      nudge_y = -0.082,
      size = 4.2
    ) 
  
  
    ### density population map
  ddd <- mu.df
  ddd$densityPop <- densityPop[match(ddd$BFS_NUMMER, densityPop$OFSKey), 'PopByKm2']
  # hack to put the 0.05 quantile densityPop for NA densityPop muni
  ddd[which(is.na(ddd$densityPop) & !is.na(ddd$EINWOHNERZ)), 'densityPop'] <- quantile(densityPop[,1], 0.05)
  
  map2 <- ggplot(co.df) + 
    bk_mapTheme(
      base_family = txt['base.font', lang], 
      title_family = txt['title.font', lang], 
      subtitle_family = txt['base.font', lang]
    ) +
    coord_quickmap(expand = F) + 
    geom_polygon(
      aes(x = long, y = lat, group = group), 
      size = 0.2, alpha = 0, color = border.color
    ) + 
    geom_polygon(
      data = ddd , 
      aes(x = long, y = lat, group = group, fill = log10(densityPop)), 
      size = 0) + 
    geom_polygon(
      data = la.df,  aes(x = long, y = lat, group = group),
      size = 0, fill = border.color, colour = border.color
    ) +  
    scale_fill_viridis(
      name = paste0(txt['popdensity', lang], "  "),
      labels = as.character(c(10^0, 10^1, 10^2, 10^3, 10^4)),
      discrete = F, option="A", direction = 1
    ) + 
    geom_point(
      data = largeAgglo,
      aes(x = lon, y = lat, group = 1, size = pop),         
      alpha = 0.85, colour = colourText_bkbg, shape = 1
    ) + 
    scale_size(range = c(3,7), guide = F) + 
    geom_text(
      data = largeAgglo,
      aes(x = lon, y = lat, group = 1, label = label),
      family = txt['base.font', lang],
      colour = colourText_bkbg,
      nudge_y = -0.082,
      size = 4.2
    ) 

    map1.path <- paste0("01_map_lang_" , lang, ".png")
    map2.path <- paste0("01_map_pop_" , lang, ".png")      
    html.outfile <- paste0("01_map_langPopForeigners_", lang, ".html")
    
    png(map1.path,  res = 200, pointsize = 1, height = 1070 * 1.1, 
        width = 1100 * 1.1, bg = '#1a0000')
    print(lmap)
    dev.off()     
    png(map2.path,  res = 200, pointsize = 1, height = 970 * 1.1, 
        width = 1100 * 1.1, bg = '#1a0000')
    print(map2)
    dev.off()   
    
    ### plot interactive foreigner map ###
    ddd <- cbind(ge.df, fo.df[match(ge.df$BFSNR, fo.df$BFS_NUMMER),] %>% 
      select(-location, -BFS_NUMMER, -foreigners))
    
    ddd$tip <- paste0(
      '<b>', as.character(ddd$GEMNAME), '</b><br>',
      '<b>', ddd$pcForeigners * 100, '%</b>, population: ', ddd$population, '<br>',
      '<div class="tipchart">', 
      '<span class="tipspanstyle">Nationalité des étrangers en %</span>
  <table>
    <tr class="tiprow">
      <td class="tipbarticks">', "Italie", '</td>',
  '<td class="tipbardiv"><div class="tipbar" style="width:%dpx;">', 
  ifelse(is.na(ddd$Italie*100), 0, ddd$Italie*100) , '</div></td>
    </tr>
    <tr class="tiprow">
      <td class="tipbarticks">', "Allemagne",'</td>',
  '<td class="tipbardiv"><div class="tipbar" style="width:%dpx;">',
  ifelse(is.na(ddd$Allemagne*100), 0, ddd$Allemagne *100), '</div></td>
    </tr>
   </table>
</div>'
    )
    
    ddd$tip <- gsub("'", "_", gsub("\\\n", "", ddd$tip))
    
    fmap <- ggplot(ddd) + 
      geom_polygon_interactive( 
        aes(x =long, y = lat, group = group, 
            fill = pcForeigners, data_id = BFSNR, 
            tooltip = tip), colour = NA
    ) + 
      bk_mapTheme() +  coord_quickmap(expand = F) + 
    geom_polygon(data = la.df,  aes(x = long, y = lat, group = group),
      size = 0, fill = border.color, colour = border.color
    ) +  
      scale_fill_viridis(
       # name = paste0(txt['popdensity', lang], "  "),
      #  labels = as.character(c(10^0, 10^1, 10^2, 10^3, 10^4)),
        direction = 1
    )
    
    imap <- ggiraph(code = {print(fmap)}, width = "100%", zoom_max = 2)
    
    save_html(
      tags$html(
        tags$head(includeHTML("styles.html")),
        tags$body(    
          # h2(txt["main.title", lang]),
          # div(class = "descr", HTML(txt["subtitle1", lang])),
          # h3(txt["h3", lang]),
          div(class="container",
              div(class="graphic", imap)
          ),
          # div(id = "footer", HTML(txt["caption", lang])),
          # div(id = "cite", HTML(footer)),
          HTML(iframeresizer)  
        )), file = paste0("test_supermap.html")
    )
     
}

```
